FROM node:18

WORKDIR /app

# Copiamos dependencias primero (para aprovechar cache de Docker)
COPY package*.json ./
RUN npm install -g @angular/cli && npm install --legacy-peer-deps

# Copiamos el resto del código
COPY . .

# Exponemos el puerto que usa ng serve
EXPOSE 4200

# Arrancamos Angular en modo dev
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
