version: "3.9"
services:
  mysql:
    image: mysql:8.1 
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      LOWER_CASE_TABLE_NAMES: 1
    volumes:
      - ./database:/docker-entrypoint-initdb.d 
